google_drive:
  root_folder_id: 1tNu_Ge0u4IL4auqFP7VBtDxVSUwtqEF_
  remote_name: vllab13
  structure: separate_anno_raw
extraction:
  subjects:
  - '0026'
  performances:
  - s1_all
  - e0
  cameras: &id001
  - 21
  - 22
  - 23
  - 24
  - 25
  - 26
  - 27
  - 28
  - 29
  - 30
  - 31
  - 32
  - 36
  - 49
  - 51
  - 54
  modalities:
  - metadata
  - calibration
  - images
  - masks
  - audio
  - keypoints2d
  - keypoints3d
  - flame
  - uv_textures
  - scan
  - scan_masks
  separate_sources: true
  camera_selection:
    type: 16cam_optimal
    count: 16
    camera_list: *id001
storage:
  temp_dir: /ssd4/zhuoyuan/renderme360_temp/temp_smc/
  output_dir: /ssd4/zhuoyuan/renderme360_temp/test_download/subjects/
  manifest_path: /ssd4/zhuoyuan/renderme360_temp/test_download/MANIFEST_21ID.csv
  log_dir: /ssd4/zhuoyuan/renderme360_temp/test_download/logs/
processing:
  delete_smc_after_extraction: true
  verify_extraction: true
  force_reextract: false
  max_retries: 3
  retry_delay: 30
limits:
  max_temp_size_gb: 200
  min_free_space_gb: 100
