# RenderMe360 21ID Dataset Extraction Configuration - 20 Camera Selection
# This configuration uses the 20-camera comprehensive selection for audio-driven avatar research
# Based on Phase 2 camera selection analysis

# Google Drive Configuration
google_drive:
  # Personal Google Drive folder ID with "Copy of" prefixed files
  root_folder_id: "1iJtwc7Z266Zwnm0q_cRALk90nBI1ETzH"  # Your personal drive copy

  # Rclone remote configuration name (already configured)
  remote_name: "vllab13"

  # Structure type for 21ID dataset (different from 500ID)
  structure: "separate_anno_raw"  # 21ID has anno/ and raw/ folders at root

# Extraction Configuration
extraction:
  # List of subjects to process (21ID dataset subjects)
  # Start with one subject for testing, then expand
  subjects:
    - "0026"  # Test subject (confirmed has data)
    # Full list of 21 subjects available in the dataset:
    # - "0041"
    # - "0048"
    # - "0094"
    # - "0099"
    # - "0100"
    # - "0116"
    # - "0156"
    # - "0168"
    # - "0175"
    # - "0189"
    # - "0195"
    # - "0232"
    # - "0250"
    # - "0253"
    # - "0259"
    # - "0262"
    # - "0278"
    # - "0290"
    # - "0295"
    # - "0297"

  # Performances to extract
  # Speech performances for audio-driven avatar research
  performances:
    - "s1_all"  # Speech performance 1
    # - "s2_all"  # Speech performance 2
    # - "s3_all"  # Speech performance 3
    # - "s4_all"  # Speech performance 4
    # - "s5_all"  # Speech performance 5
    # - "s6_all"  # Speech performance 6
    # Expression performances (commented out for speech focus):
    # - "e0"      # Expression performance 0
    # - "e1"      # Expression performance 1
    # - "e2"      # Expression performance 2
    # - "e3"      # Expression performance 3
    # - "e4"      # Expression performance 4
    # - "e5"      # Expression performance 5
    # - "e6"      # Expression performance 6
    # - "e7"      # Expression performance 7
    # - "e8"      # Expression performance 8
    # - "e9"      # Expression performance 9
    # - "e10"     # Expression performance 10
    # - "e11"     # Expression performance 11
    # - "h0"      # Head rotation

  # Camera selection - 20 cameras optimized for facial coverage
  # Based on Phase 2 analysis: front-dense selection with 360° coverage
  # Front hemisphere (face): cameras 21-32, 54-56 (14 cameras)
  # Profile views: cameras 36, 37 (2 cameras)
  # Rear hemisphere: cameras 0, 49, 51 (3 cameras)
  # Plus camera 28 for wider context
  cameras: [0, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 36, 37, 49, 51, 54, 55, 56]

  # Data modalities to extract
  # Select which types of data to extract
  modalities:
    - "metadata"      # Actor info, camera info, capture metadata
    - "calibration"   # Camera calibration matrices
    - "images"        # RGB images from cameras
    - "masks"         # Segmentation masks
    - "audio"         # Audio track (speech performances only)
    - "keypoints2d"   # 2D facial landmarks (cameras 18-32)
    - "keypoints3d"   # 3D facial landmarks
    # Expression-specific modalities (only for 'e' performances):
    - "flame"         # FLAME face model parameters
    - "uv_textures"   # UV texture maps
    - "scan"          # 3D scan mesh
    - "scan_masks"    # Scan visibility masks

  # Whether to separate anno and raw data in output
  separate_sources: true  # Creates from_anno/ and from_raw/ folders

# Storage Configuration
storage:
  # Temporary directory for downloaded SMC bundles
  # Make sure this has enough space for temporary files (50-100GB)
  temp_dir: "/ssd4/zhuoyuan/renderme360_temp/temp_smc/"

  # Output directory for extracted data
  # This will contain subject folders with extracted performances
  output_dir: "/ssd4/zhuoyuan/renderme360_temp/test_download/subjects/"

  # Path to manifest CSV for tracking extraction progress
  manifest_path: "/ssd4/zhuoyuan/renderme360_temp/test_download/MANIFEST_21ID.csv"

  # Directory for log files
  log_dir: "/ssd4/zhuoyuan/renderme360_temp/test_download/logs/"

# Processing Configuration
processing:
  # Whether to delete SMC files after successful extraction
  # Set to true to save space during streaming extraction
  delete_smc_after_extraction: true

  # Whether to verify extraction completeness
  verify_extraction: true

  # Force re-extraction even if already completed
  # Set to true to overwrite existing extractions
  force_reextract: false

  # Number of retry attempts for failed downloads
  max_retries: 3

  # Delay between retry attempts (seconds)
  retry_delay: 30

# Safety Limits
limits:
  # Maximum size for temp directory (GB)
  # Prevents filling up disk with temporary files
  max_temp_size_gb: 200

  # Minimum free space required to continue (GB)
  # Stops extraction if disk space is too low
  min_free_space_gb: 100

# Selective Extraction Examples (uncomment to use)
#
# Example 1: Extract only specific subjects
# extraction:
#   subjects:
#     - "0026"
#     - "0041"
#     - "0048"
#
# Example 2: Extract only images without masks
# extraction:
#   modalities:
#     - "metadata"
#     - "calibration"
#     - "images"
#     - "audio"
#
# Example 3: Extract single performance for testing
# extraction:
#   performances:
#     - "s1_all"

# Notes:
# 1. This config uses 20 cameras selected for optimal facial coverage
#    - Based on Phase 2 camera selection analysis
#    - Provides ~94GB per subject (1.94TB for all 21 subjects)
#    - Balances storage constraints with quality requirements
#
# 2. Google Drive structure for 21ID:
#    Your personal drive has "Copy of " prefix on all files:
#    RenderMe-360_release/
#    ├── anno/
#    │   ├── 0026/
#    │   │   ├── Copy of 0026_e0_anno.smc
#    │   │   ├── Copy of 0026_s1_all_anno.smc
#    │   │   └── ...
#    │   └── [other subjects]/
#    └── raw/
#        ├── 0026/
#        │   ├── Copy of 0026_e0_raw.smc
#        │   ├── Copy of 0026_s1_all_raw.smc
#        │   └── ...
#        └── [other subjects]/
#
# 3. The extraction script handles the "Copy of " prefix automatically
#    - Tries normal filename first (for public drive compatibility)
#    - Falls back to "Copy of " version if not found
#    - Saves locally without prefix for clean extraction
#
# 4. Output structure will be:
#    subjects/
#    └── 0026/
#        └── s1_all/
#            ├── from_anno/
#            │   ├── metadata/
#            │   ├── calibration/
#            │   ├── masks/
#            │   ├── keypoints2d/
#            │   └── keypoints3d/
#            ├── from_raw/
#            │   ├── images/
#            │   │   ├── cam_00/
#            │   │   ├── cam_21/
#            │   │   └── ... (20 cameras)
#            │   └── audio/
#            └── .extraction_complete
#
# 5. Start with subject 0026 to test:
#    python extract_subject_FULL_both.py --config config_21id_20cam.yaml --subject 0026 --performance s1_all
#
# 6. Monitor disk space during extraction
#    Each subject with 20 cameras: ~94GB
#    Full dataset (21 subjects): ~1.94TB
#
# 7. The MANIFEST_21ID.csv will track all extractions
#    Check this file to see progress and any errors